services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.aws:/root/.aws
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_REGION=ap-northeast-1
      - AWS_ENDPOINT=http://ministack:4566
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - ministack

  ministack:
    image: ministackorg/ministack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - AWS_DEFAULT_REGION=ap-northeast-1
